### ISSUE TITLE
Meteor 3 support

### ISSUE THREAD

**Issue by harry-73** [JorgenVatle/meteor-vite#127]
Hi,

Does `vite-bundler` support Meteor 3?

My tests:

- I run Meteor 2.15
- `meteor create --vue testMeteor3`
- I update `meteor-vite` to `1.10.0` and `jorgenvatle::vite-bundler` to `1.12.9`
- `meteor update --release 3.0-beta.4`
- I run `meteor`, I have the following error:

```
[[[[[ ~/Dev/vueFeaturesFlags ]]]]]            

=> Started proxy.                             
=> Started HMR server.                        
=> Errors prevented startup:                  
   
   While loading plugin `vite` from package `jorgenvatle:vite-bundler`:
   packages/modules-runtime.js:222:12: Cannot find module 'fibers'
   at makeMissingError (packages/modules-runtime.js:222:12)
   at Module.require (packages/modules-runtime.js:241:17)
   at require (packages/modules-runtime.js:258:21)
   at module (packages/promise.js:41:7)
   at fileEvaluate (packages/modules-runtime.js:336:7)
   at Module.require (packages/modules-runtime.js:238:14)
   at require (packages/modules-runtime.js:258:21)
   at packages/promise.js:149:15
   at packages/promise.js:156:3
   
   
=> Your application has errors. Waiting for file change.
```

**Comment by harry-73** [comment]
I find the release `jorgenvatle:vite-bundler@2.0.0-beta.8`. I will try it

**Comment by JorgenVatle** [comment]
Yeah, while the internals are the same, Atmosphere packages published with Meteor v2 appear to sneak in a Fibers dependency. So we have to publish a separate version for Meteor v3 users. 👍 Though the beta release might be a little behind now. If you run into any issues use `meteor-vite@1.9.0` which is known to work with `jorgenvatle:vite-bundler@2.0.0-beta.8`
